// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbtVn1MJ2wB6bmX2dyFJvO7FnT7MmXljE',
    appId: '1:950526449356:web:2a9dea981f6d688f305469',
    messagingSenderId: '950526449356',
    projectId: 'settle-now-340017',
    authDomain: 'settle-now-340017.firebaseapp.com',
    databaseURL: 'https://settle-now-340017-default-rtdb.firebaseio.com',
    storageBucket: 'settle-now-340017.appspot.com',
    measurementId: 'G-MM5228ZH88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtlYc95qPY8qlPHXrQsEpIqelijQHSt8',
    appId: '1:950526449356:android:1fdb7eebae5c7c9e305469',
    messagingSenderId: '950526449356',
    projectId: 'settle-now-340017',
    databaseURL: 'https://settle-now-340017-default-rtdb.firebaseio.com',
    storageBucket: 'settle-now-340017.appspot.com',
  );
}
