// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyCbZzOmzL2ihGAPdbLxadyIT9tu8kFwatY",
      authDomain: "settlenow-dev.firebaseapp.com",
      projectId: "settlenow-dev",
      storageBucket: "settlenow-dev.firebasestorage.app",
      messagingSenderId: "373327328514",
      appId: "1:373327328514:web:7329624402a47fed577e1b",
      measurementId: "G-0GBR0RT491");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE5v23Yn_sGYVtdicuCNxA8TMHR_AUzAE',
    appId: '1:373327328514:android:3dab1f669dd307d0577e1b',
    messagingSenderId: '373327328514',
    projectId: 'settlenow-dev',
    databaseURL: 'https://settlenow-dev-default-rtdb.firebaseio.com',
    storageBucket: 'settlenow-dev.appspot.com',
  );
}
