name: settlenow
description: A Finance Management App

publish_to: 'none'

version: 1.2.2+45

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  http: ^0.13.5
  fluttertoast: ^8.0.8
  flutter_launcher_icons: ^0.9.2
  url_launcher: ^6.0.18
  google_fonts: ^3.0.1
  font_awesome_flutter: ^9.2.0
  provider: ^6.0.2
  encrypt: ^5.0.1
  device_info_plus: ^4.1.2
  share_plus: ^4.4.0
  image_picker: ^0.8.5+3
  googleapis: ^7.0.0
  google_sign_in: ^5.4.2
  pie_chart: ^5.1.0
  firebase_analytics: ^9.1.1
  firebase_core: ^1.12.0
  flutter_local_notifications: ^9.4.0
  firebase_messaging: ^11.2.10
  firebase_dynamic_links: ^4.3.8
  package_info_plus: ^1.4.3+1
  path_provider: ^2.0.10
  dio: ^4.0.6
  in_app_update: ^3.0.0
  cached_network_image: ^3.2.2
  flutter_slidable: ^2.0.0
  in_app_review: ^2.0.4
  intl: ^0.17.0
  internet_connection_checker: ^1.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  image_path: "assets/icon/SN_WBG.png"
  flutter_lints: ^1.0.0
  

flutter:
  uses-material-design: true

  assets:
    - "assets/Images/"
    - "assets/icon/"
