name: settlenow_v2
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.12.0
  firebase_messaging: ^15.2.3
  go_router: ^15.1.2
  email_validator: ^3.0.0
  iconsax: ^0.0.8
  auto_size_text: ^3.0.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  omni_datetime_picker: ^2.1.1
  http: ^1.3.0
  intl: ^0.20.2
  url_launcher: ^6.3.1
  shimmer: ^3.0.0
  provider: ^6.1.2
  moment_dart: ^5.2.3
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  google_sign_in: ^6.3.0
  device_preview: ^1.2.0
  firebase_analytics: ^11.4.5
  fl_chart: ^1.0.0
  flutter_sticky_header: ^0.8.0
  flutter_speed_dial: ^7.0.0
  encrypt: ^5.0.3
  device_info_plus: ^11.4.0
  dart_jsonwebtoken: ^3.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  change_app_package_name: ^1.4.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - "assets/icon/"
    - "assets/Images/"
    - "assets/sn/"
    - "assets/socialmedia/"
