name: settlenow
description: A Finance Management App

publish_to: 'none'

version: 1.3.6+90

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.11
  http: ^0.13.5
  fluttertoast: ^8.0.8
  url_launcher: ^6.0.18
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  provider: ^6.0.2
  encrypt: ^5.0.1
  device_info_plus: ^8.2.0
  share_plus: ^6.3.2
  image_picker: ^0.8.5+3
  googleapis: ^10.1.0
  google_sign_in: ^6.0.1
  firebase_analytics: ^10.2.1
  firebase_core: ^2.10.0
  firebase_messaging: ^14.4.1
  firebase_dynamic_links: ^5.1.1
  package_info_plus: ^3.1.0
  path_provider: ^2.0.10
  dio: ^5.1.1
  in_app_update: ^4.0.1
  cached_network_image: ^3.2.2
  intl: ^0.17.0
  internet_connection_checker: ^1.0.0+1
  in_app_review: ^2.0.6
  flutter_sms_inbox: ^1.0.2
  permission_handler: ^10.2.0
  app_settings: ^4.1.8
  shimmer: ^2.0.0
  syncfusion_flutter_charts: ^21.1.41
  awesome_notifications: ^0.7.4+1
  image_cropper: ^3.0.1
  auto_size_text: ^3.0.0
  omni_datetime_picker: ^0.0.3+1
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true

  assets:
    - "assets/Images/"
    - "assets/icon/"
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/res/values/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/
    - android/app/src/main/res/drawable-hdpi/
    - android/app/src/main/res/drawable-mdpi/
    - android/app/src/main/res/drawable-xhdpi/
    - android/app/src/main/res/drawable-xxhdpi/
    - android/app/src/main/res/drawable-xxxhdpi/
    - android/app/src/main/res/mipmap-anydpi-v26/